baseURL = '/'
contentdir = "content"
locale = 'fr-fr'
DefaultContentLanguage = "en"
title = 'GdBlog'
theme = 'PaperMod'


[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About me"
url = "/pages/about"
weight = 3

[[menu.main]]
name = "Github"
url = "https://github.com/GdXcIi"
weight = 4
